import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/CustomNavBar'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import type { Database } from '@/types/supabase'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`h-full`}>
      <body className={`${inter.className} h-full`}>
        <div className='flex flex-col h-full'>
          <Navbar />
          <main className='pt-[68px] flex flex-col grow'>{children}</main>
          {/* <div>footer</div> */}
        </div>
      </body>
    </html>
  )
}
