export const SELECT_RECORD_SIZE = 12
export const MAX_IMG = 5
export const IMG_URL_PREFIX = `https://yspdxycvowpczkmwskfj.supabase.co/storage/v1/object/public/car-img/`
export const CAR_PATH_NAME = `/cars`
export const EDIT_LIST_PATH_NAME = `/editList`
export const EDIT_FORM = `EDIT`
export const SELL_FORM = `SELL`
export const IMG_BUCKET_NAME = `car-img`
export const DEFAULT_GRID_IMG = `CONTINENTAL_FLYING_SPUR.jpg`
export const SORT_LIST = ['Latest', 'Highest Price', 'Lowest Price']
